print(2 + 3)  # addition(+)
print(3 - 1)  # sbstraction(-)
print(2 * 3)  # multiplication(*)
print(3 / 2)  # division(/)
print(3**2)  # exponential(**)
print(3 % 2)  # modulus(%)
print(3 // 2)  # floor division operator(//)
